# Generated by Django 6.0.1 on 2026-05-19 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('concessions', '0001_initial'),
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingconcession',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_concessions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingconcession',
            name='concession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concessions.concession'),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.seat'),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='theaters.showtime'),
        ),
        migrations.AddField(
            model_name='seathold',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.seat'),
        ),
        migrations.AddField(
            model_name='seathold',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.showtime'),
        ),
        migrations.AddField(
            model_name='seathold',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookingseat',
            unique_together={('showtime', 'seat')},
        ),
        migrations.AlterUniqueTogether(
            name='seathold',
            unique_together={('showtime', 'seat')},
        ),
    ]
