# Generated by Django 6.0.1 on 2026-05-19 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('momo', 'MoMo'), ('vnpay', 'VNPay'), ('zalopay', 'ZaloPay'), ('cash', 'Tiền mặt')], default='cash', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('success', 'Thành công'), ('failed', 'Thất bại'), ('refunded', 'Hoàn tiền')], default='pending', max_length=20)),
                ('transaction_code', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
        ),
    ]
