# Generated by Django 6.0.1 on 2026-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('success', 'Thành công'), ('failed', 'Thất bại'), ('refunded', 'Hoàn tiền')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
