# Generated by Django 6.0.1 on 2026-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showtime',
            options={'ordering': ['start_time']},
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['room', 'start_time'], name='theaters_sh_room_id_fc597f_idx'),
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['movie', 'start_time'], name='theaters_sh_movie_i_d8ff5f_idx'),
        ),
    ]
