# Generated by Django 6.0.1 on 2026-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_alter_showtime_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
