# Generated by Django 6.0.1 on 2026-05-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_alter_showtime_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
