# Generated by Django 6.0.1 on 2026-05-20 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concession',
            name='is_active',
        ),
        migrations.AddField(
            model_name='concession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concession',
            name='status',
            field=models.CharField(choices=[('selling', 'Đang bán'), ('stopped', 'Ngừng bán')], default='selling', max_length=20),
        ),
        migrations.AlterField(
            model_name='concession',
            name='description',
            field=models.TextField(default='Chưa có mô tả'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concession',
            name='price',
            field=models.IntegerField(),
        ),
    ]
